### PR TITLE
ShowOnMenu can now be used to show and hide pages on the site menu

### PR DESCRIPTION
**Pull request by mgdesign**
Following the example of https://github.com/ryanlelek/Raneto/pull/223/commits from @dgarcia202 I've added a "ShowOnMenu" options, to allow to filter which pages can be present on the menu and which one shouldn't. In this case too, all pages behave following a default setting, and are visible in not set otherwise.

When the page is not visibile in the site menu, it is still active and visible by visiting the url. 

I've also updated the test to include the new feature, using the existing one as a guideline.

### CODE REVIEW

**Comment by mgdesign** [comment]
cc @stickgrinder

**Comment by stickgrinder** [comment]
@ryanlelek, any news on the possibility of having this merged?

**Comment by ryanlelek** [comment]
@stickgrinder @mgdesign 
Yep, looks fine. Let me do a maintenance release first and then I'll make a new release with these changes after some quick testing. This will allow people to easily rollback if there are any issues while we integrate

**Comment by ryanlelek** [comment]
@mgdesign Thank you for your (first) contribution Marcello!
Expect it to be live in 24-48 hours in v0.17.8 on npm

**Pull request merged**
